server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: your professional email
    password: Set your password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      logging:
        level:
          org.springframework.mail.javamail: DEBUG


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # ddl-auto: update
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE

